# Name of the GitHub Actions workflow
name: Terraform AWS CI/CD

# Trigger this workflow on push to main branch and on pull requests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Apply for AWS Infrastructure
    runs-on: ubuntu-latest  # GitHub-hosted Ubuntu runner

    # GitHub permissions required for OIDC and PR commenting (optional)
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    # Environment variables
    env:
      AWS_REGION: us-east-1
      TF_VERSION: 1.6.6

    steps:
      # Step 1: Checkout the code from GitHub repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # Step 3: Set AWS credentials from GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 4: Initialize the Terraform working directory
      - name: Terraform Init
        run: terraform init

      # Step 5: Check Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -check

      # Step 6: Validate Terraform code
      - name: Terraform Validate
        run: terraform validate

      # Step 7: Generate Terraform plan and save to a file
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan.binary

      # Step 8: Show the plan in readable format
      - name: Terraform Plan Summary
        run: terraform show -no-color tfplan.binary

      # Step 9: Apply the plan automatically **only on the main branch**
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan.binary
